export type argsType =  // ALl possible args type.
  | "User Mention"
  | "Role Mention"
  | "Channel Mention"
  | "GuildID"
  | "UserID"
  | "ChannelID"
  | "RoleID"
  | "Text"
  | "Number"
  | "Time"
  | "Color"
  | "Code"
  | "Reason"
  | "Prefix"
  | "other"; // Union Types
